Master
Kicer86/github_api pull request #4
Opened 2022-05-25 23:25 UTC by kevinmukuna

Hey. I have modified connection.cpp to allow pagination. i have also added docstring. i also ran lint on the file to meet cpp and rest api standards.

2022-05-26 18:14 UTC, Kicer86 requested changes

2022-05-26 18:14 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +std::pair <std::string, int> checkPaginationLInk(const std::string& header);
What is the reason of this declaration?

2022-05-26 18:14 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +std::string finalResult;  // combination of result
Global variables should be avoided.

2022-05-26 18:14 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +std::pair <std::string, int> checkPaginationLInk(const std::string& header) {
hide it in anonymous namespace

2022-05-26 18:14 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +    , m_token(token) {
I'd prefer original format style ( "{" in new line ) which is consistent with rest files in this project

2022-05-26 18:14 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +        // itereating through each word in line, words are seperate by space
separate -> separated

2022-05-26 18:14 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +std::string GitHub::CurlBackend::Connection::get(const std::string& request) {
This method became quite big. It should be split.

2022-05-26 18:14 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +            std::cout << "yes" << std::endl;
looks like a debug message

2022-05-26 18:14 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +        if (header_links.find("link") != std::string::npos) {
It may be clearer to use ternary operator here instead of this if statement.

2022-05-26 18:14 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +            paginate = false;
Seems to be not needed

2022-05-27 05:16 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +std::string finalResult;  // combination of result
Also, afaik, it is not being used.

2022-05-29 11:53 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +std::pair <std::string, int> checkPaginationLInk(const std::string& header) {
Also there is a typo in function name

2022-05-29 11:54 UTC, Kicer86 commented on src/curl_backend/connection.cpp
> +std::pair <std::string, int> checkPaginationLInk(const std::string& header) {
Additionally please extract (possibly) each loop into a new function for cleaner code

2022-05-30 08:52 UTC, kevinmukuna commented
Hey Mical,

I had travelled to go watch the champions league.

I’ll modify the code and push the changes after work



> On 29 May 2022, at 12:54, Michał Walenciak ***@***.***> wrote:
> 
> ﻿
> @Kicer86 commented on this pull request.
> 
> In src/curl_backend/connection.cpp:
> 
> >  }
>  
> -
> -std::string GitHub::CurlBackend::Connection::get(const std::string& request)
> -{
> +std::pair <std::string, int> checkPaginationLInk(const std::string& header);
> +/**
> + * @brief the method takes in a http header and returns 
> + *        the next link used for pagination and the 
> + *        number of pages 
> + * 
> + * @param header header data from the return data from 
> + *               the api call 
> + * @return std::pair <std::string, int> the last link 
> + *         and the number of page 
> + */
> +std::pair <std::string, int> checkPaginationLInk(const std::string& header) {
> Additionally please extract (possibly) each loop into a new function for cleaner code
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2022-05-30 18:06 UTC, kevinmukuna commented on src/curl_backend/connection.cpp
> +    , m_token(token) {
i've reformatted the code to meet your style and the rest of the api

2022-05-30 18:06 UTC, kevinmukuna commented on src/curl_backend/connection.cpp
> +std::string finalResult;  // combination of result
resolved

2022-05-30 18:06 UTC, kevinmukuna commented on src/curl_backend/connection.cpp
> +std::pair <std::string, int> checkPaginationLInk(const std::string& header) {
done

2022-05-30 18:07 UTC, kevinmukuna commented on src/curl_backend/connection.cpp
> +std::string GitHub::CurlBackend::Connection::get(const std::string& request) {
done

2022-05-30 18:07 UTC, kevinmukuna commented on src/curl_backend/connection.cpp
> +        if (header_links.find("link") != std::string::npos) {
got rid of it...

2022-05-30 18:13 UTC, kevinmukuna reviewed
i've changed the code to meet your request. let me know if they meet your requirement. i've altered the file a bit but i've kept your original code, just moved it into a diff function

2022-06-04 13:30 UTC, merged